services:
  doniaiimage:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "7878:7878"
    environment:
      - PORT=7878
      - NODE_ENV=production
      - SESSION_SECRET=t6M4Xu32jZN0lf7gBz0tEDnDwQ4Zt42boQW2dHZU
    volumes:
      - ./data:/app/data
      - ./uploads:/app/uploads
    restart: unless-stopped
